/*
 * Exercise3_2.java
 *
 * Created on April 16, 2002, 9:32 PM
 */

package exercise3_2;

/**
 *
 * @author  administrator
 */
public class Exercise3_2 extends javax.swing.JApplet {
  
  /** Creates new form Exercise3_2 */
  public Exercise3_2() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    memoryWatch1 = new exercise3_2.MemoryWatch();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    memoryWatch1.addMemoryListener(new exercise3_2.MemoryListener() {
      public void sufficientMemory(exercise3_2.MemoryEvent evt) {
        memoryWatch1SufficientMemory(evt);
      }
      public void insufficientMemory(exercise3_2.MemoryEvent evt) {
        memoryWatch1InsufficientMemory(evt);
      }
    });

    jScrollPane1.setViewportView(jTextArea1);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents

  private void memoryWatch1SufficientMemory(exercise3_2.MemoryEvent evt) {//GEN-FIRST:event_memoryWatch1SufficientMemory
    sufficientMemory(evt);
  }//GEN-LAST:event_memoryWatch1SufficientMemory

  private void memoryWatch1InsufficientMemory(exercise3_2.MemoryEvent evt) {//GEN-FIRST:event_memoryWatch1InsufficientMemory
    insufficientMemory(evt);
  }//GEN-LAST:event_memoryWatch1InsufficientMemory
  
  public void sufficientMemory(MemoryEvent e) {
    jTextArea1.setText("Sufficient Memory");
    jTextArea1.append("highLimit " + memoryWatch1.getHighLimit()+"\n");
    jTextArea1.append("free memory " + e.freeMemory() + "\n");
    jTextArea1.append("total memory " + e.totalMemory() + "\n");
  }

  public void insufficientMemory(MemoryEvent e) {
    jTextArea1.setText("Insufficient Memory\n");
    jTextArea1.append("lowLimit " + memoryWatch1.getLowLimit()+"\n");
    jTextArea1.append("free memory " + e.freeMemory() + "\n");
    jTextArea1.append("total memory " + e.totalMemory() + "\n");
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private exercise3_2.MemoryWatch memoryWatch1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
  
}
