/*
 * Exercise8_2.java
 *
 * Created on April 19, 2002, 1:22 PM
 */

package exercise8_2;

import exercise8_1.*;
import javax.swing.*;

public class Exercise8_2 extends javax.swing.JApplet {
  
  // Create an array of strings for figure names
  String[] figures = {"Square", "Rectangle", "Circle", "Oval"};

  // Create a list cell renderer
  ListCellRenderer myListCellRenderer = new MyListCellRenderer();

  /** Creates new form Exercise8_2 */
  public Exercise8_2() {
    initComponents();

    jComboBox1.addItem("Square");
    jComboBox1.addItem("Rectangle");
    jComboBox1.addItem("Circle");
    jComboBox1.addItem("Oval");
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jComboBox1 = new javax.swing.JComboBox();
    figurePanel = new exercise6_5.FigurePanel();

    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    getContentPane().add(jComboBox1, java.awt.BorderLayout.NORTH);

    getContentPane().add(figurePanel, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String figure = (String)(jComboBox1.getSelectedItem());

    if (figure.equals("Square"))
      figurePanel.setFigureType(1);
    else if (figure.equals("Rectangle"))
      figurePanel.setFigureType(2);
    else if (figure.equals("Circle"))
      figurePanel.setFigureType(3);
    else if (figure.equals("Oval"))
      figurePanel.setFigureType(4);

    figurePanel.repaint();
  }//GEN-LAST:event_jComboBox1ActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBox1;
  private exercise6_5.FigurePanel figurePanel;
  // End of variables declaration//GEN-END:variables
  
}
