package serializationdemo;

import messagepaneldemo.MessagePanel;
import java.io.*;
import java.util.Date;
import java.awt.*;

public class SerializationApplication extends javax.swing.JFrame {
  
  /** Creates new form SerializationApplication */
  public SerializationApplication() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jlblStatus = new javax.swing.JLabel();
        jpSerialization = new javax.swing.JPanel();
        jpRadioButtons = new javax.swing.JPanel();
        jrbRed = new javax.swing.JRadioButton();
        jrbGreen = new javax.swing.JRadioButton();
        jrbYellow = new javax.swing.JRadioButton();
        jpButtons = new javax.swing.JPanel();
        jbtStore = new javax.swing.JButton();
        jbtRestore = new javax.swing.JButton();
        jbrLeft = new javax.swing.JButton();
        jbtRight = new javax.swing.JButton();
        messagePanel1 = new messagepaneldemo.MessagePanel();
        
        
        setTitle("Serialization Application");
        addWindowListener(new java.awt.event.WindowAdapter() {
          public void windowClosing(java.awt.event.WindowEvent evt) {
            exitForm(evt);
          }
        });
        
        jlblStatus.setText("jLabel1");
        getContentPane().add(jlblStatus, java.awt.BorderLayout.SOUTH);
        
        jpSerialization.setLayout(new java.awt.BorderLayout());
        
        jpRadioButtons.setBorder(new javax.swing.border.EtchedBorder());
        jrbRed.setText("Red");
        buttonGroup1.add(jrbRed);
        jrbRed.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jrbRedActionPerformed(evt);
          }
        });
        
        jpRadioButtons.add(jrbRed);
        
        jrbGreen.setText("Green");
        buttonGroup1.add(jrbGreen);
        jrbGreen.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jrbGreenActionPerformed(evt);
          }
        });
        
        jpRadioButtons.add(jrbGreen);
        
        jrbYellow.setText("Yellow");
        buttonGroup1.add(jrbYellow);
        jrbYellow.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jrbYellowActionPerformed(evt);
          }
        });
        
        jpRadioButtons.add(jrbYellow);
        
        jpSerialization.add(jpRadioButtons, java.awt.BorderLayout.NORTH);
      
      jbtStore.setText("Store");
        jbtStore.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbtStoreActionPerformed(evt);
          }
        });
        
        jpButtons.add(jbtStore);
        
        jbtRestore.setText("Restore");
        jbtRestore.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbtRestoreActionPerformed(evt);
          }
        });
        
        jpButtons.add(jbtRestore);
        
        jbrLeft.setText("<=");
        jbrLeft.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbrLeftActionPerformed(evt);
          }
        });
        
        jpButtons.add(jbrLeft);
        
        jbtRight.setText("=>");
        jbtRight.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbtRightActionPerformed(evt);
          }
        });
        
        jpButtons.add(jbtRight);
        
        jpSerialization.add(jpButtons, java.awt.BorderLayout.SOUTH);
      
      messagePanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
      jpSerialization.add(messagePanel1, java.awt.BorderLayout.CENTER);
      
      getContentPane().add(jpSerialization, java.awt.BorderLayout.CENTER);
    
    pack();
  }//GEN-END:initComponents
  
  private void jbtRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRightActionPerformed
    messagePanel1.moveRight();
  }//GEN-LAST:event_jbtRightActionPerformed
  
  private void jbrLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrLeftActionPerformed
    messagePanel1.moveLeft();
  }//GEN-LAST:event_jbrLeftActionPerformed
  
  private void jbtRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRestoreActionPerformed
    try {
      ObjectInputStream in =
      new ObjectInputStream(new FileInputStream("beans.dat"));
      MessagePanel c = (MessagePanel)in.readObject();
      Date d = (Date)in.readObject();
      jpSerialization.remove(messagePanel1);
      messagePanel1 = c;
      jpSerialization.add(messagePanel1, BorderLayout.CENTER);
      jpSerialization.repaint();
      in.close();
      jlblStatus.setText("The object saved at " + d.toString()
      + " is restored");
    }
    catch (IOException ex1) {
      System.out.println(ex1);
    }
    catch (ClassNotFoundException ex2) {
      System.out.println(ex2);
    }
  }//GEN-LAST:event_jbtRestoreActionPerformed
  
  private void jbtStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtStoreActionPerformed
    try {
      ObjectOutputStream out =
      new ObjectOutputStream(new FileOutputStream("beans.dat"));
      out.writeObject(messagePanel1);
      out.writeObject(new Date());
      out.close();
      jlblStatus.setText("The object is stored in beans.dat");
    }
    catch (IOException ex) {
      System.out.println(ex);
    }
  }//GEN-LAST:event_jbtStoreActionPerformed
  
  private void jrbYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbYellowActionPerformed
    messagePanel1.setBackground(Color.yellow);
  }//GEN-LAST:event_jrbYellowActionPerformed
  
    private void jrbGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGreenActionPerformed
      messagePanel1.setBackground(Color.green);
    }//GEN-LAST:event_jrbGreenActionPerformed
    
    private void jrbRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRedActionPerformed
      messagePanel1.setBackground(Color.red);
    }//GEN-LAST:event_jrbRedActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      new SerializationApplication().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JPanel jpSerialization;
    private javax.swing.JPanel jpRadioButtons;
    private javax.swing.JRadioButton jrbRed;
    private javax.swing.JRadioButton jrbGreen;
    private javax.swing.JRadioButton jrbYellow;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JButton jbtStore;
    private javax.swing.JButton jbtRestore;
    private javax.swing.JButton jbrLeft;
    private javax.swing.JButton jbtRight;
    private messagepaneldemo.MessagePanel messagePanel1;
    // End of variables declaration//GEN-END:variables
    
}
