package corbademo;


/**
* corbademo/Student.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from C:/radft/corbademo/Student.idl
* Saturday, September 15, 2001 9:34:22 PM EDT
*/


// Student.idl
public interface Student extends StudentOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Student
