package corbademo;


/**
* corbademo/StudentOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from C:/radft/corbademo/Student.idl
* Saturday, September 15, 2001 9:34:22 PM EDT
*/


// Student.idl
public interface StudentOperations 
{
  double findScore (String name);
} // interface StudentOperations
