/*
 * DisplayFigure.java
 *
 * Created on September 7, 2001, 2:55 PM
 */

package displayfiguredemo;

/**
 *
 * @author  administrator
 */
public class DisplayFigure extends javax.swing.JApplet {

  /** Creates new form DisplayFigure */
    public DisplayFigure() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jtpFigures = new javax.swing.JTabbedPane();
        squarePanel = new displayfiguredemo.FigurePanel();
        rectanglePanel = new displayfiguredemo.FigurePanel();
        circlePanel = new displayfiguredemo.FigurePanel();
        ovalPanel = new displayfiguredemo.FigurePanel();
        
        jtpFigures.addTab("Square", squarePanel);
        
        rectanglePanel.setFigureType(2);
        jtpFigures.addTab("Rectangle", rectanglePanel);
        
        circlePanel.setFigureType(3);
        jtpFigures.addTab("Circle", circlePanel);
        
        ovalPanel.setFigureType(4);
        jtpFigures.addTab("Oval", ovalPanel);
        
        getContentPane().add(jtpFigures, java.awt.BorderLayout.CENTER);
      
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jtpFigures;
    private displayfiguredemo.FigurePanel squarePanel;
    private displayfiguredemo.FigurePanel rectanglePanel;
    private displayfiguredemo.FigurePanel circlePanel;
    private displayfiguredemo.FigurePanel ovalPanel;
    // End of variables declaration//GEN-END:variables

}
