package comboboxdemo;

import java.awt.*;
import imageviewerdemo.ImageViewer;

public class TestComboBox extends javax.swing.JApplet {  
    // Create images
    Image imageUS = ImageViewer.createImage(
    "/image/us.gif", this);
    Image imageFrance = ImageViewer.createImage(
    "/image/fr.gif", this);
    Image imageUK = ImageViewer.createImage(
    "/image/uk.gif", this);
    Image imageGermany = ImageViewer.createImage(
    "/image/germany.gif", this);
    Image imageIndia = ImageViewer.createImage(
    "/image/india.gif", this);
    Image imageNorway = ImageViewer.createImage(
    "/image/norway.gif", this);
    Image imageChina = ImageViewer.createImage(
    "/image/china.gif", this);
    Image imageCanada = ImageViewer.createImage(
    "/image/ca.gif", this);
    Image imageDenmark = ImageViewer.createImage(
    "/image/denmark.gif", this);
 
    MyComboBoxModel comboBoxModel = new MyComboBoxModel(new String[]
    {"United States", "France",
     "United Kingdom", "Germany",
     "India", "Norway", "China", "Canada", "Denmark"},
     new Image[]
     {imageUS, imageFrance, imageUK, imageGermany, imageIndia,
      imageNorway, imageChina, imageCanada, imageDenmark});;

  // Create a list cell renderer
  MyComboBoxRenderer myComboBoxRenderer = new MyComboBoxRenderer();

  /** Creates new form TestComboBox */
  public TestComboBox() {
    initComponents();
    
        
      // Set list model
      jcboCountries.setModel(comboBoxModel);
      
      // Set list cell renderer
      jcboCountries.setRenderer(myComboBoxRenderer);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jcboCountries = new javax.swing.JComboBox();
    imageViewer1 = new guipropertyeditordemo.ImageViewer();
    
    jcboCountries.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jcboCountriesActionPerformed(evt);
      }
    });
    
    getContentPane().add(jcboCountries, java.awt.BorderLayout.NORTH);
    
    getContentPane().add(imageViewer1, java.awt.BorderLayout.CENTER);
    
  }//GEN-END:initComponents

    private void jcboCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboCountriesActionPerformed
    Image image = comboBoxModel.getImage(
      jcboCountries.getSelectedItem());
    imageViewer1.setImage(image);
    }//GEN-LAST:event_jcboCountriesActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcboCountries;
    private guipropertyeditordemo.ImageViewer imageViewer1;
    // End of variables declaration//GEN-END:variables
}