package displaycolordemo;

public class DisplayColor extends javax.swing.JApplet {  
  // Declare color component values
  int redValue, greenValue, blueValue;
  java.awt.Color color;

  /** Creates new form DisplayColor */
  public DisplayColor() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jpSelections = new javax.swing.JPanel();
    jpLabels = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jpSliders = new javax.swing.JPanel();
    jslRed = new javax.swing.JSlider();
    jslGreen = new javax.swing.JSlider();
    jslBlue = new javax.swing.JSlider();
    jpColor = new javax.swing.JPanel();

    jpSelections.setLayout(new java.awt.BorderLayout());

    jpSelections.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
    jpLabels.setLayout(new java.awt.GridLayout(3, 0));

    jLabel1.setText("Red");
    jpLabels.add(jLabel1);

    jLabel2.setText("Green");
    jpLabels.add(jLabel2);

    jLabel3.setText("Blue");
    jpLabels.add(jLabel3);

    jpSelections.add(jpLabels, java.awt.BorderLayout.WEST);

    jpSliders.setLayout(new java.awt.GridLayout(3, 0));

    jslRed.setMaximum(128);
    jslRed.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jslRedStateChanged(evt);
      }
    });

    jpSliders.add(jslRed);

    jslGreen.setMaximum(128);
    jslGreen.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jslGreenStateChanged(evt);
      }
    });

    jpSliders.add(jslGreen);

    jslBlue.setMaximum(128);
    jslBlue.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jslBlueStateChanged(evt);
      }
    });

    jpSliders.add(jslBlue);

    jpSelections.add(jpSliders, java.awt.BorderLayout.CENTER);

    getContentPane().add(jpSelections, java.awt.BorderLayout.SOUTH);

    getContentPane().add(jpColor, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents
  
  private void jslBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslBlueStateChanged
    blueValue = jslBlue.getValue();
    updateColor();
  }//GEN-LAST:event_jslBlueStateChanged
  
    private void jslGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslGreenStateChanged
      greenValue = jslGreen.getValue();
      updateColor();
    }//GEN-LAST:event_jslGreenStateChanged
    
    private void jslRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslRedStateChanged
      redValue = jslRed.getValue();
      updateColor();
    }//GEN-LAST:event_jslRedStateChanged
    
    void updateColor() {
      color = new java.awt.Color(redValue, greenValue, blueValue);
      jpColor.setBackground(color);
    }
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jpColor;
  private javax.swing.JSlider jslBlue;
  private javax.swing.JPanel jpLabels;
  private javax.swing.JSlider jslRed;
  private javax.swing.JPanel jpSelections;
  private javax.swing.JPanel jpSliders;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JSlider jslGreen;
  // End of variables declaration//GEN-END:variables
}