package toolbardemo;

public class TestToolBar extends javax.swing.JApplet {
  /** Creates new form TestToolBar */
  public TestToolBar() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
      jToolBar1 = new javax.swing.JToolBar();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      
      jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new.gif")));
      jButton1.setToolTipText("New");
      jToolBar1.add(jButton1);
      
      jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open.gif")));
      jButton2.setToolTipText("Open");
      jToolBar1.add(jButton2);
      
      jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.gif")));
      jButton3.setToolTipText("Print");
      jButton3.setMargin(new java.awt.Insets(2, 2, 4, 4));
      jToolBar1.add(jButton3);
      
      getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);
    
  }//GEN-END:initComponents
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  // End of variables declaration//GEN-END:variables
}