/*
 * TestClock.java
 *
 * Created on August 30, 2001, 10:47 PM
 */

package clockdemo;

/**
 *
 * @author  administrator
 */
public class TestClock extends javax.swing.JApplet {

  /** Creates new form TestClock */
    public TestClock() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  private void initComponents() {//GEN-BEGIN:initComponents
    clock1 = new clockdemo.Clock();

    clock1.setDateStyle(2);
    getContentPane().add(clock1, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private clockdemo.Clock clock1;
  // End of variables declaration//GEN-END:variables

}
