package jdbcdemo;

import java.sql.*;

public class AddressPanel extends javax.swing.JPanel {
  // Database connection passed from DBConnectDialog
  Connection connection;
  
  /** Construct an AddressPanel with a specified connection */
  public AddressPanel(Connection connection) {
    this();
    this.connection = connection;
    jlblStatus.setText("Using static SQL statements");
  }
  
  /** Creates new form AddressPanel */
  public AddressPanel() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
      jlblStatus = new javax.swing.JLabel();
      jpButtons = new javax.swing.JPanel();
      jbtSearch = new javax.swing.JButton();
      jbtInsert = new javax.swing.JButton();
      jbtClear = new javax.swing.JButton();
      jpAddress = new javax.swing.JPanel();
      jPanel3 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jtfFirstName = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jtfMi = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      jtfLastName = new javax.swing.JTextField();
      jPanel4 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      jtfStreet = new javax.swing.JTextField();
      jPanel5 = new javax.swing.JPanel();
      jLabel6 = new javax.swing.JLabel();
      jtfCity = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      jtfState = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      jtfZip = new javax.swing.JTextField();
      jPanel6 = new javax.swing.JPanel();
      jLabel9 = new javax.swing.JLabel();
      jtfTelephone = new javax.swing.JTextField();
      jPanel7 = new javax.swing.JPanel();
      jLabel10 = new javax.swing.JLabel();
      jtfEmail = new javax.swing.JTextField();
      
      setLayout(new java.awt.BorderLayout());
      
      add(jlblStatus, java.awt.BorderLayout.SOUTH);
      
      jbtSearch.setText("Search");
      jbtSearch.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jbtSearchActionPerformed(evt);
        }
      });
      
      jpButtons.add(jbtSearch);
      
      jbtInsert.setText("Insert");
      jbtInsert.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jbtInsertActionPerformed(evt);
        }
      });
      
      jpButtons.add(jbtInsert);
      
      jbtClear.setText("Clear");
      jbtClear.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jbtClearActionPerformed(evt);
        }
      });
      
      jpButtons.add(jbtClear);
      
      add(jpButtons, java.awt.BorderLayout.NORTH);
        
        jpAddress.setLayout(new java.awt.GridLayout(5, 0));
        
        jpAddress.setBorder(new javax.swing.border.TitledBorder("Address"));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel2.setText("First Name");
        jPanel3.add(jLabel2);
        
        jtfFirstName.setColumns(10);
        jPanel3.add(jtfFirstName);
        
        jLabel3.setText("MI");
        jPanel3.add(jLabel3);
        
        jtfMi.setColumns(1);
        jPanel3.add(jtfMi);
        
        jLabel4.setText("Last Name");
        jPanel3.add(jLabel4);
        
        jtfLastName.setColumns(15);
        jPanel3.add(jtfLastName);
        
        jpAddress.add(jPanel3);
      
      jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel5.setText("Street");
        jPanel4.add(jLabel5);
        
        jtfStreet.setColumns(37);
        jPanel4.add(jtfStreet);
        
        jpAddress.add(jPanel4);
      
      jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel6.setText("City");
        jPanel5.add(jLabel6);
        
        jtfCity.setColumns(10);
        jPanel5.add(jtfCity);
        
        jLabel7.setText("State");
        jPanel5.add(jLabel7);
        
        jtfState.setColumns(2);
        jPanel5.add(jtfState);
        
        jLabel8.setText("ZIP");
        jPanel5.add(jLabel8);
        
        jtfZip.setColumns(5);
        jPanel5.add(jtfZip);
        
        jpAddress.add(jPanel5);
      
      jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel9.setText("Telephone");
        jPanel6.add(jLabel9);
        
        jtfTelephone.setColumns(12);
        jPanel6.add(jtfTelephone);
        
        jpAddress.add(jPanel6);
      
      jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel10.setText("Email");
        jPanel7.add(jLabel10);
        
        jtfEmail.setColumns(20);
        jPanel7.add(jtfEmail);
        
        jpAddress.add(jPanel7);
      
      add(jpAddress, java.awt.BorderLayout.CENTER);
    
  }//GEN-END:initComponents
  
  private void jbtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearActionPerformed
    clear();
  }//GEN-LAST:event_jbtClearActionPerformed
  
    private void jbtInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInsertActionPerformed
      insert();
    }//GEN-LAST:event_jbtInsertActionPerformed
    
    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
      select();
    }//GEN-LAST:event_jbtSearchActionPerformed
    
    protected void select() {
      String query = "select * from Address where " +
      "firstName = " +
      "'" + jtfFirstName.getText().trim() + "'" +
      " and lastName = " +
      "'" + jtfLastName.getText().trim() + "'";
      
      try {
        Statement stmt = connection.createStatement();
        ResultSet rs = stmt.executeQuery(query);
        
        if (rs.next()) {
          jtfMi.setText(rs.getString(2));
          jtfStreet.setText(rs.getString(4));
          jtfCity.setText(rs.getString(5));
          jtfState.setText(rs.getString(6));
          jtfZip.setText(rs.getString(7));
          jtfTelephone.setText(rs.getString(8));
          jtfEmail.setText(rs.getString(9));
          
          jlblStatus.setText("Record found");
        }
        else {
          jlblStatus.setText("Record not found");
        }
      }
      catch (SQLException ex) {
        jlblStatus.setText(ex.getMessage());
      }
    }
    
    protected void insert() {
      String sqlInsert = "insert into Address values (" +
      "'" + jtfFirstName.getText().trim() + "'" + "," +
      "'" + jtfMi.getText().trim() + "'" + "," +
      "'" + jtfLastName.getText().trim() + "'" + "," +
      "'" + jtfStreet.getText().trim() + "'" + "," +
      "'" + jtfCity.getText().trim() + "'" + "," +
      "'" + jtfState.getText().trim() + "'" + "," +
      "'" + jtfZip.getText().trim() + "'" + "," +
      "'" + jtfTelephone.getText().trim() + "'" + "," +
      "'" + jtfEmail.getText().trim()+ "'" + ")";
      
      try {
        Statement stmt = connection.createStatement();
        int t = stmt.executeUpdate(sqlInsert);
        jlblStatus.setText("Insertion succeeded");
      }
      catch (SQLException ex) {
        jlblStatus.setText(ex.getMessage());
      }
    }
    
    protected void clear() {
      jtfFirstName.setText(null);
      jtfMi.setText(null);
      jtfLastName.setText(null);
      jtfStreet.setText(null);
      jtfCity.setText(null);
      jtfState.setText(null);
      jtfZip.setText(null);
      jtfTelephone.setText(null);
      jtfEmail.setText(null);
    }
    
    /** Set status */
    public void setStatus(String msg) {
      jlblStatus.setText(msg);
    }

    /** Return firstnmae */
    public String getFirstName() {
      return jtfFirstName.getText().trim();
    }
    
    /** Set firstnmae */
    public void setFirstName(String s) {
      jtfFirstName.setText(s);
    }

    /** Return lastnmae */
    public String getMi() {
      return jtfMi.getText().trim();
    }
    
    /** Set mi */
    public void setMi(String s) {
      jtfMi.setText(s);
    }

    /** Return lastnmae */
    public String getLastName() {
      return jtfLastName.getText().trim();
    } 
    
    /** Set lastnmae */
    public void setLastName(String s) {
      jtfLastName.setText(s);
    }

    /** Return street */
    public String getStreet() {
      return jtfStreet.getText().trim();
    } 
    
    /** Set street */
    public void setStreet(String s) {
      jtfStreet.setText(s);
    }    
        
    /** Return city */
    public String getCity() {
      return jtfCity.getText().trim();
    } 
    
    /** Set city */
    public void setCity(String s) {
      jtfCity.setText(s);
    }
        
    /** Return zip */
    public String getZip() {
      return jtfZip.getText().trim();
    } 
    
    /** Set zip */
    public void setZip(String s) {
      jtfZip.setText(s);
    }
    
    /** Return state */
    public String getState() {
      return jtfState.getText().trim();
    } 
    
    /** Set state */
    public void setState(String s) {
      jtfState.setText(s);
    }
    
    /** Return telephone */
    public String getTelephone() {
      return jtfTelephone.getText().trim();
    } 
    
    /** Set telephone */
    public void setTelephone(String s) {
      jtfTelephone.setText(s);
    }
    
    /** Return email */
    public String getEmail() {
      return jtfEmail.getText().trim();
    } 
    
    /** Set email */
    public void setEmail(String s) {
      jtfEmail.setText(s);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JButton jbtInsert;
    private javax.swing.JButton jbtClear;
    private javax.swing.JPanel jpAddress;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtfFirstName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfMi;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtfLastName;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtfStreet;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtfCity;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtfState;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jtfZip;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfTelephone;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField jtfEmail;
    // End of variables declaration//GEN-END:variables
}