package jdbcdemo;

import java.sql.*;
import java.util.*;

public class TestTableEditor extends javax.swing.JFrame {
  /** Creates new form TestTableEditor */
  public TestTableEditor() {
    initComponents();
    
    // Add items to the combo boxes
    jcboURL.addItem("jdbc:odbc:LiangBookDB_MDB");
    jcboURL.addItem(
    "jdbc:oracle:thin:@liang.armstrong.edu:1521:test");
    jcboURL.addItem
    ("jdbc:borland:dslocal:C:\\radjb4\\LiangBookDB.jds");
    jcboURL.addItem
    ("jdbc:interbase://localhost/C:/radjb4/LiangBookDB.gdb");
    jcboDriver.addItem("sun.jdbc.odbc.JdbcOdbcDriver");
    jcboDriver.addItem("oracle.jdbc.driver.OracleDriver");
    jcboDriver.addItem(
    "com.borland.datastore.jdbc.DataStoreDriver");
    jcboDriver.addItem("interbase.interclient.Driver");
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
        jlblStatus = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jbtConnect = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jcboDriver = new javax.swing.JComboBox();
        jcboURL = new javax.swing.JComboBox();
        jtfUserName = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jtfTableName = new javax.swing.JTextField();
        tableEditor1 = new jdbcdemo.TableEditor();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
          public void windowClosing(java.awt.event.WindowEvent evt) {
            exitForm(evt);
          }
        });
        
        getContentPane().add(jlblStatus, java.awt.BorderLayout.SOUTH);
        
        jPanel1.setLayout(new java.awt.BorderLayout());
        
        jbtConnect.setText("Connect to DB & Get Table");
        jbtConnect.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbtConnectActionPerformed(evt);
          }
        });
        
        jPanel1.add(jbtConnect, java.awt.BorderLayout.SOUTH);
        
        jPanel2.setLayout(new java.awt.GridLayout(5, 0));
          
          jLabel1.setText("JDBC Driver");
          jPanel2.add(jLabel1);
          
          jLabel2.setText("Database URL");
          jPanel2.add(jLabel2);
          
          jLabel3.setText("Username");
          jPanel2.add(jLabel3);
          
          jLabel4.setText("Password");
          jPanel2.add(jLabel4);
          
          jLabel5.setText("Table Name");
          jPanel2.add(jLabel5);
          
          jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);
        
        jPanel3.setLayout(new java.awt.GridLayout(5, 0));
          
          jPanel3.add(jcboDriver);
          
          jPanel3.add(jcboURL);
          
          jPanel3.add(jtfUserName);
          
          jPanel3.add(jpfPassword);
          
          jPanel3.add(jtfTableName);
          
          jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);
        
        jSplitPane1.setLeftComponent(jPanel1);
      
      jSplitPane1.setRightComponent(tableEditor1);
      
      getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);
    
    pack();
  }//GEN-END:initComponents
  
    private void jbtConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConnectActionPerformed
      try {
        // Connect to the database
        Connection connection = getConnection();
        tableEditor1.setConnectionAndTable(connection,
        jtfTableName.getText().trim());
      }
      catch (Exception ex) {
        jlblStatus.setText(ex.toString());
      }
    }//GEN-LAST:event_jbtConnectActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      new TestTableEditor().show();
    }
    
    /** Connect to a database */
    private Connection getConnection() throws Exception {
      // Load the JDBC driver
      System.out.println((String)jcboDriver.getSelectedItem());
      Class.forName(((String)jcboDriver.getSelectedItem()).trim());
      System.out.println("Driver loaded");
      
      // Establish a connection
      Connection connection = DriverManager.getConnection
      (((String)jcboURL.getSelectedItem()).trim(),
      jtfUserName.getText().trim(), jpfPassword.getText().trim());
      System.out.println("Database connected");
      jlblStatus.setText("Database connected");
      
      return connection;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtConnect;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox jcboDriver;
    private javax.swing.JComboBox jcboURL;
    private javax.swing.JTextField jtfUserName;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfTableName;
    private jdbcdemo.TableEditor tableEditor1;
    // End of variables declaration//GEN-END:variables
}