package dialogdemo;

public class TestCustomDialog extends javax.swing.JApplet {
  ColorDialog colorDialog1 = new ColorDialog();
  
  /** Creates new form TestCustomDialog */
  public TestCustomDialog() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    private void initComponents() {//GEN-BEGIN:initComponents
      jbtChangeColor = new javax.swing.JButton();
      
      getContentPane().setLayout(new java.awt.FlowLayout());
      
      jbtChangeColor.setText("Change Button Text Color");
      jbtChangeColor.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jbtChangeColorActionPerformed(evt);
        }
      });
      
      getContentPane().add(jbtChangeColor);
      
    }//GEN-END:initComponents
    
    private void jbtChangeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtChangeColorActionPerformed
      colorDialog1.setVisible(true);
      
      if (colorDialog1.getColor() != null)
        jbtChangeColor.setForeground(colorDialog1.getColor());
    }//GEN-LAST:event_jbtChangeColorActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtChangeColor;
    // End of variables declaration//GEN-END:variables
}