package boundconstraintpropertydemo;

public class TestBoundPropertySupportClass extends javax.swing.JFrame {
  /** Creates new form TestBoundPropertySupportClass */
  public TestBoundPropertySupportClass() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    editor = new boundconstraintpropertydemo.ClockEditorUsingSupportClass();
    clock = new boundconstraintpropertydemo.ClockBoundPropertyListener();
    
    setTitle("TestBoundPropertySupportClass");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });
    
    editor.setBorder(new javax.swing.border.TitledBorder("Clock Property Editor"));
    editor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        editorPropertyChange(evt);
      }
    });
    
    getContentPane().add(editor, java.awt.BorderLayout.CENTER);
    
    getContentPane().add(clock, java.awt.BorderLayout.WEST);
    
    pack();
  }//GEN-END:initComponents
    
    private void editorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_editorPropertyChange
      clock.propertyChange(evt);
    }//GEN-LAST:event_editorPropertyChange
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      new TestBoundPropertySupportClass().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundconstraintpropertydemo.ClockEditorUsingSupportClass editor;
    private boundconstraintpropertydemo.ClockBoundPropertyListener clock;
    // End of variables declaration//GEN-END:variables
    
}
