/*
 * Exercise1_2.java
 *
 * Created on August 30, 2001, 2:50 PM
 */

package exercise1_2;

/**
 *
 * @author  administrator
 */
public class Exercise1_2 extends javax.swing.JApplet {

  /** Creates new form Exercise1_2 */
    public Exercise1_2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jbtConvert = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCelsius = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfFahrenheit = new javax.swing.JTextField();
        
        jbtConvert.setText("Convert");
        jbtConvert.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbtConvertActionPerformed(evt);
          }
        });
        
        getContentPane().add(jbtConvert, java.awt.BorderLayout.SOUTH);
        
        jLabel1.setText("Celsius");
        jPanel1.add(jLabel1);
        
        jtfCelsius.setColumns(4);
        jPanel1.add(jtfCelsius);
        
        jLabel2.setText("Fahrenheit");
        jPanel1.add(jLabel2);
        
        jtfFahrenheit.setColumns(4);
        jPanel1.add(jtfFahrenheit);
        
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
      
    }//GEN-END:initComponents

    private void jbtConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConvertActionPerformed
      double celsius = Double.parseDouble(jtfCelsius.getText());
      double fahrenheit = (9.0/5.0)*celsius + 32.0;
      jtfFahrenheit.setText(new Double(fahrenheit).toString());
    }//GEN-LAST:event_jbtConvertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtConvert;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtfCelsius;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtfFahrenheit;
    // End of variables declaration//GEN-END:variables

}
