package menudemo;

public class TestMenuDesigner extends javax.swing.JApplet {
  /** Creates new form TestMenuDesigner */
  public TestMenuDesigner() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiNew = new javax.swing.JMenuItem();
        jmiOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jmiPrint = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jmiExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        softwareHelpSubMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        hardwareSubMenu = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        colorHelpSubMenu = new javax.swing.JMenu();
        jrbmiBlue = new javax.swing.JRadioButtonMenuItem();
        jrbmiYellow = new javax.swing.JRadioButtonMenuItem();
        jrbmiRed = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        
        jMenu1.setText("File");
        jmiNew.setMnemonic(78);
        jmiNew.setText("New");
        jmiNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new.gif")));
        jMenu1.add(jmiNew);
        jmiOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmiOpen.setText("Open");
        jmiOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open.gif")));
        jmiOpen.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiOpenActionPerformed(evt);
          }
        });
        
        jMenu1.add(jmiOpen);
        jMenu1.add(jSeparator1);
        jmiPrint.setMnemonic(80);
        jmiPrint.setText("Print");
        jMenu1.add(jmiPrint);
        jMenu1.add(jSeparator2);
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiExitActionPerformed(evt);
          }
        });
        
        jMenu1.add(jmiExit);
        jMenuBar1.add(jMenu1);
      jMenu2.setText("Help");
          softwareHelpSubMenu.setText("Software");
          jMenuItem3.setText("Unix");
          softwareHelpSubMenu.add(jMenuItem3);
          jMenuItem4.setText("NT");
          softwareHelpSubMenu.add(jMenuItem4);
          jMenuItem5.setText("Win95");
          softwareHelpSubMenu.add(jMenuItem5);
          jMenu2.add(softwareHelpSubMenu);
        hardwareSubMenu.setText("Hardware");
        jMenu2.add(hardwareSubMenu);
        jCheckBoxMenuItem1.setText("CheckBox");
        jMenu2.add(jCheckBoxMenuItem1);
        colorHelpSubMenu.setText("Menu");
          jrbmiBlue.setText("RadioButton");
          buttonGroup1.add(jrbmiBlue);
          colorHelpSubMenu.add(jrbmiBlue);
          jrbmiYellow.setText("RadioButton");
          buttonGroup1.add(jrbmiYellow);
          colorHelpSubMenu.add(jrbmiYellow);
          jrbmiRed.setText("RadioButton");
          buttonGroup1.add(jrbmiRed);
          colorHelpSubMenu.add(jrbmiRed);
          jMenu2.add(colorHelpSubMenu);
        jMenuBar1.add(jMenu2);
      
    setJMenuBar(jMenuBar1);
  }//GEN-END:initComponents
  
    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed
    
    private void jmiOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOpenActionPerformed
      // Add your handling code here:
    }//GEN-LAST:event_jmiOpenActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jmiNew;
    private javax.swing.JMenuItem jmiOpen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem jmiPrint;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu softwareHelpSubMenu;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu hardwareSubMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu colorHelpSubMenu;
    private javax.swing.JRadioButtonMenuItem jrbmiBlue;
    private javax.swing.JRadioButtonMenuItem jrbmiYellow;
    private javax.swing.JRadioButtonMenuItem jrbmiRed;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}