package introdemo;

public class TestUIApplet extends javax.swing.JApplet {
  /** Creates new form TestUIApplet */
  public TestUIApplet() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    private void initComponents() {//GEN-BEGIN:initComponents
        jbtAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlblNum1 = new javax.swing.JLabel();
        jtfNum1 = new javax.swing.JTextField();
        jlbNum2 = new javax.swing.JLabel();
        jtfNum2 = new javax.swing.JTextField();
        jlblResult = new javax.swing.JLabel();
        jtfResult = new javax.swing.JTextField();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jbtAdd.setText("Add");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        getContentPane().add(jbtAdd, new java.awt.GridBagConstraints());

        jlblNum1.setText("Number 1");
        jPanel1.add(jlblNum1);

        jtfNum1.setColumns(4);
        jPanel1.add(jtfNum1);

        jlbNum2.setText("Number 2");
        jPanel1.add(jlbNum2);

        jtfNum2.setColumns(4);
        jPanel1.add(jtfNum2);

        jlblResult.setText("Result");
        jPanel1.add(jlblResult);

        jtfResult.setColumns(5);
        jPanel1.add(jtfResult);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

    }//GEN-END:initComponents
  
    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
      int num1 =
        (Integer.valueOf(jtfNum1.getText().trim())).intValue();
      int num2 =
        (Integer.valueOf(jtfNum2.getText().trim())).intValue();
      int result = num1 + num2;
      
      // Display result
      jtfResult.setText(String.valueOf(result));
    }//GEN-LAST:event_jbtAddActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbNum2;
    private javax.swing.JTextField jtfNum2;
    private javax.swing.JTextField jtfNum1;
    private javax.swing.JTextField jtfResult;
    private javax.swing.JLabel jlblNum1;
    private javax.swing.JLabel jlblResult;
    private javax.swing.JButton jbtAdd;
    // End of variables declaration//GEN-END:variables

  /** Main method */
  public static void main(String[] args) {
    TestUIApplet applet = new TestUIApplet();
    javax.swing.JFrame frame = new javax.swing.JFrame();
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setTitle("TestUIApplet");
    frame.getContentPane().add(applet, java.awt.BorderLayout.CENTER);
    frame.setSize(400,320);
    java.awt.Dimension d = 
      java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    frame.setLocation((d.width - frame.getSize().width) / 2, 
      (d.height - frame.getSize().height) / 2);
    frame.setVisible(true);
  }
}