package exercise4_4;

public class Exercise4_4 extends javax.swing.JApplet {
  /** Creates new form Exercise4_4 */
  public Exercise4_4() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    rectangleModel1 = new exercise4_4.RectangleModel();
    rectangleEditor1 = new exercise4_4.RectangleEditor();
    rectangleView1 = new exercise4_4.RectangleView();

    rectangleModel1.setFilled(true);
    rectangleModel1.setHeight(300.0);
    rectangleModel1.setWidth(23.0);

    rectangleEditor1.setModel(rectangleModel1);
    getContentPane().add(rectangleEditor1, java.awt.BorderLayout.NORTH);

    rectangleView1.setModel(rectangleModel1);
    getContentPane().add(rectangleView1, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private exercise4_4.RectangleView rectangleView1;
  private exercise4_4.RectangleModel rectangleModel1;
  private exercise4_4.RectangleEditor rectangleEditor1;
  // End of variables declaration//GEN-END:variables
}