/*
 * RectangleEditor.java
 *
 * Created on April 17, 2002, 6:54 AM
 */

package exercise4_4;

import java.awt.event.*;

public class RectangleEditor extends javax.swing.JPanel implements ActionListener {
  
  /** Holds value of property model. */
  private RectangleModel model;
  
  /** Creates new form RectangleEditor */
  public RectangleEditor() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jLabel1 = new javax.swing.JLabel();
    jtfWidth = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jtfHeight = new javax.swing.JTextField();

    setLayout(new java.awt.GridLayout(2, 0));

    jLabel1.setText("Width");
    add(jLabel1);

    jtfWidth.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jtfWidthActionPerformed(evt);
      }
    });

    add(jtfWidth);

    jLabel2.setText("Height");
    add(jLabel2);

    jtfHeight.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jtfHeightActionPerformed(evt);
      }
    });

    add(jtfHeight);

  }//GEN-END:initComponents

  private void jtfHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHeightActionPerformed
    model.setHeight(Double.parseDouble(jtfHeight.getText()));
  }//GEN-LAST:event_jtfHeightActionPerformed

  private void jtfWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWidthActionPerformed
    model.setWidth(Double.parseDouble(jtfWidth.getText()));
  }//GEN-LAST:event_jtfWidthActionPerformed

  /** Getter for property model.
   * @return Value of property model.
   */
  public RectangleModel getModel() {
    return this.model;
  }  
  
  /** Setter for property model.
   * @param model New value of property model.
   */
  public void setModel(RectangleModel model) {
    this.model = model;

    if (model != null) {
      // Register the view as listener for the model
      model.addActionListener(this);
    }
  }  
  
  public void actionPerformed(java.awt.event.ActionEvent actionEvent) {
    if (model != null) {
      if (actionEvent.getActionCommand().equals("width"))
        jtfWidth.setText(
          new Double(model.getWidth()).toString());
      if (actionEvent.getActionCommand().equals("height"))
        jtfHeight.setText(
          new Double(model.getHeight()).toString());
    }
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField jtfHeight;
  private javax.swing.JTextField jtfWidth;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
  
}
