/*
 * TestCircle.java
 *
 * Created on August 26, 2001, 10:46 PM
 */

package beaninfodemo;

/**
 *
 * @author  administrator
 */
public class TestCircle extends javax.swing.JApplet {

  /** Creates new form TestCircle */
    public TestCircle() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
      circle1 = new beaninfodemo.Circle();
      
      circle1.writeRadius(60);
      getContentPane().add(circle1, java.awt.BorderLayout.CENTER);
      
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private beaninfodemo.Circle circle1;
    // End of variables declaration//GEN-END:variables

}
