// DisplayMap.java: Display maps in a label placed in a scroll pane
package displaymapdemo;

import imageviewerdemo.ImageViewer;
import javax.swing.*;

public class DisplayMap extends javax.swing.JApplet {
  javax.swing.ImageIcon map1;
  javax.swing.ImageIcon map2;

  /** Creates new form DisplayMap */
  public DisplayMap() {
    initComponents();
    
    // Load images
    map1 = ImageViewer.createImageIcon(
      "/image/indianaMap.gif", this);
    map2 = ImageViewer.createImageIcon("/image/ohioMap.gif", this);
    javax.swing.ImageIcon hRuler = ImageViewer.createImageIcon(
      "/image/horizontalRuler.gif", this);
    javax.swing.ImageIcon vRuler = ImageViewer.createImageIcon(
      "/image/verticalRuler.gif", this);
    
    // Set row header, column header and corner header
    jspMap.setColumnHeaderView(new JLabel(hRuler));
      jspMap.setRowHeaderView(new JLabel(vRuler));
    jspMap.setCorner(JScrollPane.UPPER_LEFT_CORNER,
      new CornerPanel(JScrollPane.UPPER_LEFT_CORNER));
    jspMap.setCorner(ScrollPaneConstants.UPPER_RIGHT_CORNER,
      new CornerPanel(JScrollPane.UPPER_RIGHT_CORNER));
    jspMap.setCorner(JScrollPane.LOWER_RIGHT_CORNER,
      new CornerPanel(JScrollPane.LOWER_RIGHT_CORNER));
    jspMap.setCorner(JScrollPane.LOWER_LEFT_CORNER,
      new CornerPanel(JScrollPane.LOWER_LEFT_CORNER));

    // Set initial image icon
    jlblMap.setIcon(map1);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
      buttonGroup1 = new javax.swing.ButtonGroup();
      jpSelection = new javax.swing.JPanel();
      jrbMap1 = new javax.swing.JRadioButton();
      jrbMap2 = new javax.swing.JRadioButton();
      jspMap = new javax.swing.JScrollPane();
      jlblMap = new javax.swing.JLabel();
      
      
      jpSelection.setBorder(new javax.swing.border.TitledBorder("Select a Map"));
      jrbMap1.setText("Indiana");
      buttonGroup1.add(jrbMap1);
      jrbMap1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jrbMap1ActionPerformed(evt);
        }
      });
      
      jpSelection.add(jrbMap1);
      
      jrbMap2.setText("Ohio");
      buttonGroup1.add(jrbMap2);
      jrbMap2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jrbMap2ActionPerformed(evt);
        }
      });
      
      jpSelection.add(jrbMap2);
      
      getContentPane().add(jpSelection, java.awt.BorderLayout.NORTH);
      
      jspMap.setViewportView(jlblMap);
      
      getContentPane().add(jspMap, java.awt.BorderLayout.CENTER);
    
  }//GEN-END:initComponents

  private void jrbMap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMap2ActionPerformed
    if (jrbMap2.isSelected()) jlblMap.setIcon(map2);
  }//GEN-LAST:event_jrbMap2ActionPerformed

  private void jrbMap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMap1ActionPerformed
    if (jrbMap1.isSelected()) jlblMap.setIcon(map1);
  }//GEN-LAST:event_jrbMap1ActionPerformed
    
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JPanel jpSelection;
  private javax.swing.JRadioButton jrbMap1;
  private javax.swing.JRadioButton jrbMap2;
  private javax.swing.JScrollPane jspMap;
  private javax.swing.JLabel jlblMap;
  // End of variables declaration//GEN-END:variables
}