/*
 * TestMessagePanel.java
 *
 * Created on August 27, 2001, 11:37 AM
 */

package messagepaneldemo;

/**
 *
 * @author  administrator
 */
public class TestMessagePanel extends javax.swing.JApplet {

  /** Creates new form TestMessagePanel */
    public TestMessagePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
      messagePanel1 = new messagepaneldemo.MessagePanel();
      
      messagePanel1.setMessage("");
      messagePanel1.setCentered(true);
      messagePanel1.setXCoordinate(50);
      messagePanel1.setYCoordinate(50);
      getContentPane().add(messagePanel1, java.awt.BorderLayout.CENTER);
      
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private messagepaneldemo.MessagePanel messagePanel1;
    // End of variables declaration//GEN-END:variables

}
