/*
 * TestMultipleMessagePanel.java
 *
 * Created on August 27, 2001, 2:57 PM
 */

package messagepaneldemo;

/**
 *
 * @author  administrator
 */
public class TestMultipleMessagePanel extends javax.swing.JApplet {
  /** Creates new form TestMultipleMessagePanel */
    public TestMultipleMessagePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
      multipleMessagePanel1 = new messagepaneldemo.MultipleMessagePanel();
      
      multipleMessagePanel1.setMessages(new String[] { "message1", "message2", "message3", "message4"});
      getContentPane().add(multipleMessagePanel1, java.awt.BorderLayout.CENTER);
      
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private messagepaneldemo.MultipleMessagePanel multipleMessagePanel1;
    // End of variables declaration//GEN-END:variables

}
