package imageviewerdemo;

import javax.swing.*;
import java.awt.*;

public class SixImages extends javax.swing.JApplet {
  /** Creates new form SixImages */
  public SixImages() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    imageViewer1 = new imageviewerdemo.ImageViewer();
    imageViewer2 = new imageviewerdemo.ImageViewer();
    imageViewer3 = new imageviewerdemo.ImageViewer();
    imageViewer4 = new imageviewerdemo.ImageViewer();
    imageViewer5 = new imageviewerdemo.ImageViewer();
    imageViewer6 = new imageviewerdemo.ImageViewer();
    
    getContentPane().setLayout(new java.awt.GridLayout(2, 0, 5, 5));
    
    imageViewer1.setImageFilename("/image/us.gif");
    getContentPane().add(imageViewer1);
    
    imageViewer2.setImageFilename("/image/ca.gif");
    getContentPane().add(imageViewer2);
    
    imageViewer3.setImageFilename("/image/india.gif");
    getContentPane().add(imageViewer3);
    
    imageViewer4.setImageFilename("/image/uk.gif");
    getContentPane().add(imageViewer4);
    
    imageViewer5.setImageFilename("/image/china.gif");
    getContentPane().add(imageViewer5);
    
    imageViewer6.setImageFilename("/image/norway.gif");
    getContentPane().add(imageViewer6);
    
  }//GEN-END:initComponents
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private imageviewerdemo.ImageViewer imageViewer1;
  private imageviewerdemo.ImageViewer imageViewer2;
  private imageviewerdemo.ImageViewer imageViewer3;
  private imageviewerdemo.ImageViewer imageViewer4;
  private imageviewerdemo.ImageViewer imageViewer5;
  private imageviewerdemo.ImageViewer imageViewer6;
  // End of variables declaration//GEN-END:variables
  
  /** Main method */
  public static void main(String[] args) {
    SixImages applet = new SixImages();
    JFrame frame = new JFrame();
    //EXIT_ON_CLOSE == 3
    frame.setDefaultCloseOperation(3);
    frame.setTitle("SixImages");
    frame.getContentPane().add(applet, BorderLayout.CENTER);
    applet.init();
    applet.start();
    frame.setSize(400,320);
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    frame.setLocation((d.width - frame.getSize().width) / 2, (d.height - frame.getSize().height) / 2);
    frame.setVisible(true);
  }
}