/*
 * Test.java
 *
 * Created on September 3, 2001, 7:54 PM
 */

package imageviewerdemo;

import javax.swing.*;
/**
 *
 * @author  administrator
 */
public class Test extends javax.swing.JApplet {

  /** Creates new form Test */
    public Test() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      
      jButton1.setText("jButton1");
      getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);
      
      jButton2.setText("jButton2");
      getContentPane().add(jButton2, java.awt.BorderLayout.NORTH);
      
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
  static {
    try {
      UIManager.setLookAndFeel(
        UIManager.getSystemLookAndFeelClassName());
      //UIManager.setLookAndFeel
      //  (UIManager.getCrossPlatformLookAndFeelClassName());
    }
    catch (Exception e) {}
  }

}
