/*
 * Exercise4_8.java
 *
 * Created on September 23, 2001, 10:56 AM
 */

package exercise4_8;

/**
 *
 * @author  administrator
 */
public class Exercise4_8 extends javax.swing.JApplet {

  /** Creates new form Exercise4_8 */
    public Exercise4_8() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
      chartModel1 = new exercise4_8.ChartModel();
      barChart1 = new exercise4_8.BarChart();
      pieChart1 = new exercise4_8.PieChart();
      
      
      getContentPane().setLayout(new java.awt.GridLayout(1, 2));
      
      barChart1.setModel(chartModel1);
      getContentPane().add(barChart1);
      
      pieChart1.setModel(chartModel1);
      getContentPane().add(pieChart1);
      
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private exercise4_8.ChartModel chartModel1;
    private exercise4_8.BarChart barChart1;
    private exercise4_8.PieChart pieChart1;
    // End of variables declaration//GEN-END:variables

}
