package viewhtmldemo;

public class ViewHTML extends javax.swing.JApplet {
  
  /** Creates new form ViewHTML */
  public ViewHTML() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    private void initComponents() {//GEN-BEGIN:initComponents
        jpURL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfURL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jep = new javax.swing.JEditorPane();
        
        jpURL.setLayout(new java.awt.BorderLayout());
        
        jLabel1.setText("URL");
        jpURL.add(jLabel1, java.awt.BorderLayout.WEST);
        
        jtfURL.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jtfURLActionPerformed(evt);
          }
        });
        
        jpURL.add(jtfURL, java.awt.BorderLayout.CENTER);
        
        getContentPane().add(jpURL, java.awt.BorderLayout.NORTH);
        
        jep.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
          public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
            jepHyperlinkUpdate(evt);
          }
        });
        
        jScrollPane1.setViewportView(jep);
        
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
      
    }//GEN-END:initComponents
    
    private void jepHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_jepHyperlinkUpdate
      try {
        jep.setPage(evt.getURL());
      }
      catch (java.io.IOException ex) {
        ex.printStackTrace();
      }
    }//GEN-LAST:event_jepHyperlinkUpdate
    
    private void jtfURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfURLActionPerformed
      try {
        // Get the URL of the HTML file
        java.net.URL url = new java.net.URL(jtfURL.getText().trim());
        
        // Display the HTML file
        jep.setPage(url);
      }
      catch (java.io.IOException ex) {
        ex.printStackTrace();
      }
    }//GEN-LAST:event_jtfURLActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpURL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtfURL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane jep;
    // End of variables declaration//GEN-END:variables
}