/*
 * Exercise5_2.java
 *
 * Created on April 17, 2002, 8:36 PM
 */

/**
 *
 * @author  administrator
 */
public class Exercise5_2 extends javax.swing.JApplet {
  
  /** Creates new form Exercise5_2 */
  public Exercise5_2() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jPanel1 = new javax.swing.JPanel();
    jchkWrap = new javax.swing.JCheckBox();
    jrbWrapWords = new javax.swing.JRadioButton();
    jrbWrapCharacters = new javax.swing.JRadioButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jta = new javax.swing.JTextArea();

    jPanel1.setBorder(new javax.swing.border.TitledBorder("Wrap Options"));
    jchkWrap.setText("Wrap");
    jchkWrap.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jchkWrapActionPerformed(evt);
      }
    });

    jPanel1.add(jchkWrap);

    jrbWrapWords.setText("Wrap Words");
    jrbWrapWords.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jrbWrapWordsActionPerformed(evt);
      }
    });

    jPanel1.add(jrbWrapWords);

    jrbWrapCharacters.setText("Wrap Characters");
    jrbWrapCharacters.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jrbWrapCharactersActionPerformed(evt);
      }
    });

    jPanel1.add(jrbWrapCharacters);

    getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

    jScrollPane1.setViewportView(jta);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents

  private void jchkWrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkWrapActionPerformed
    jta.setLineWrap(jchkWrap.isSelected());

    if (jchkWrap.isSelected()) {
      jrbWrapWords.setEnabled(true);
      jrbWrapCharacters.setEnabled(true);
    }
    else {
      jrbWrapWords.setEnabled(false);
      jrbWrapCharacters.setEnabled(false);
    }
  }//GEN-LAST:event_jchkWrapActionPerformed

  private void jrbWrapWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbWrapWordsActionPerformed
    jta.setWrapStyleWord(jrbWrapWords.isSelected());
    jta.revalidate();
  }//GEN-LAST:event_jrbWrapWordsActionPerformed

  private void jrbWrapCharactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbWrapCharactersActionPerformed
    jta.setWrapStyleWord(!jrbWrapCharacters.isSelected());
    jta.revalidate();
  }//GEN-LAST:event_jrbWrapCharactersActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JCheckBox jchkWrap;
  private javax.swing.JTextArea jta;
  private javax.swing.JRadioButton jrbWrapCharacters;
  private javax.swing.JRadioButton jrbWrapWords;
  // End of variables declaration//GEN-END:variables
  
}
