package dynamicsettingdemo;

public class DynamicSetting extends javax.swing.JApplet {
  /** Creates new form DynamicSetting */
  public DynamicSetting() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
          btg1 = new javax.swing.ButtonGroup();
          btg2 = new javax.swing.ButtonGroup();
          jpSettings = new javax.swing.JPanel();
          jpAlignment = new javax.swing.JPanel();
          jpHorizontalAlignment = new javax.swing.JPanel();
          jrbLeft = new javax.swing.JRadioButton();
          jrbCenter = new javax.swing.JRadioButton();
          jrbRight = new javax.swing.JRadioButton();
          jpVerticalAlignment = new javax.swing.JPanel();
          jrbTop = new javax.swing.JRadioButton();
          jrbVCenter = new javax.swing.JRadioButton();
          jrbBottom = new javax.swing.JRadioButton();
          jpMiscSettings = new javax.swing.JPanel();
          jchkBorderPainted = new javax.swing.JCheckBox();
          jchkContentAreaFilled = new javax.swing.JCheckBox();
          jchkEnabled = new javax.swing.JCheckBox();
          jchkFocusPainted = new javax.swing.JCheckBox();
          jchkOpaque = new javax.swing.JCheckBox();
          jchkRolloverEnabled = new javax.swing.JCheckBox();
          jpButtons = new javax.swing.JPanel();
          jbt = new javax.swing.JButton();
          jtb = new javax.swing.JToggleButton();
          jchk = new javax.swing.JCheckBox();
          jrb = new javax.swing.JRadioButton();
          
          
          jpSettings.setLayout(new java.awt.GridLayout(1, 0));
          
          jpAlignment.setLayout(new java.awt.GridLayout(2, 0));
          
          jpHorizontalAlignment.setLayout(new java.awt.GridLayout(3, 0));
          
          jpHorizontalAlignment.setBorder(new javax.swing.border.TitledBorder("Horizontal Alignment"));
          jrbLeft.setText("LEFT");
          btg1.add(jrbLeft);
          jrbLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              jrbLeftActionPerformed(evt);
            }
          });
          
          jpHorizontalAlignment.add(jrbLeft);
          
          jrbCenter.setText("CENTER");
          btg1.add(jrbCenter);
          jrbCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              jrbCenterActionPerformed(evt);
            }
          });
          
          jpHorizontalAlignment.add(jrbCenter);
          
          jrbRight.setText("RIGHT");
          btg1.add(jrbRight);
          jrbRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              jrbRightActionPerformed(evt);
            }
          });
          
          jpHorizontalAlignment.add(jrbRight);
          
          jpAlignment.add(jpHorizontalAlignment);
        
        jpVerticalAlignment.setLayout(new java.awt.GridLayout(3, 0));
          
          jpVerticalAlignment.setBorder(new javax.swing.border.TitledBorder("Vertical Alignment"));
          jrbTop.setText("TOP");
          btg2.add(jrbTop);
          jrbTop.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rbr.gif")));
          jrbTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rb.gif")));
          jrbTop.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rbp.gif")));
          jrbTop.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rbs.gif")));
          jrbTop.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rbrs.gif")));
          jrbTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              jrbTopActionPerformed(evt);
            }
          });
          
          jpVerticalAlignment.add(jrbTop);
          
          jrbVCenter.setText("CENTER");
          btg2.add(jrbVCenter);
          jrbVCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              jrbVCenterActionPerformed(evt);
            }
          });
          
          jpVerticalAlignment.add(jrbVCenter);
          
          jrbBottom.setText("BOTTOM");
          btg2.add(jrbBottom);
          jrbBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              jrbBottomActionPerformed(evt);
            }
          });
          
          jpVerticalAlignment.add(jrbBottom);
          
          jpAlignment.add(jpVerticalAlignment);
        
        jpSettings.add(jpAlignment);
      
      jpMiscSettings.setLayout(new java.awt.GridLayout(6, 0));
        
        jpMiscSettings.setBorder(new javax.swing.border.TitledBorder("Miscellaneous Options"));
        jchkBorderPainted.setText("Border Painted");
        jchkBorderPainted.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jchkBorderPaintedActionPerformed(evt);
          }
        });
        
        jpMiscSettings.add(jchkBorderPainted);
        
        jchkContentAreaFilled.setText("Content Area Filled");
        jchkContentAreaFilled.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jchkContentAreaFilledActionPerformed(evt);
          }
        });
        
        jpMiscSettings.add(jchkContentAreaFilled);
        
        jchkEnabled.setText("Enabled");
        jchkEnabled.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jchkEnabledActionPerformed(evt);
          }
        });
        
        jpMiscSettings.add(jchkEnabled);
        
        jchkFocusPainted.setText("Focus Painted");
        jchkFocusPainted.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jchkFocusPaintedActionPerformed(evt);
          }
        });
        
        jpMiscSettings.add(jchkFocusPainted);
        
        jchkOpaque.setText("Opaque");
        jchkOpaque.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jchkOpaqueActionPerformed(evt);
          }
        });
        
        jpMiscSettings.add(jchkOpaque);
        
        jchkRolloverEnabled.setText("Rollover Enabled");
        jchkRolloverEnabled.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jchkRolloverEnabledActionPerformed(evt);
          }
        });
        
        jpMiscSettings.add(jchkRolloverEnabled);
        
        jpSettings.add(jpMiscSettings);
      
      getContentPane().add(jpSettings, java.awt.BorderLayout.SOUTH);
      
      jpButtons.setLayout(new java.awt.GridLayout(2, 0));
      
      jbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b.gif")));
      jbt.setText("Button");
      jbt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/br.gif")));
      jbt.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bp.gif")));
      jpButtons.add(jbt);
      
      jtb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tb.gif")));
      jtb.setText("Toggle Button");
      jtb.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tbr.gif")));
      jtb.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tbs.gif")));
      jtb.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tbrs.gif")));
      jpButtons.add(jtb);
      
      jchk.setText("Check Box");
      jpButtons.add(jchk);
      
      jrb.setText("Radio Button");
      jrb.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rbr.gif")));
      jrb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rb.gif")));
      jrb.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rbp.gif")));
      jrb.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rbs.gif")));
      jrb.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rbrs.gif")));
      jpButtons.add(jrb);
      
      getContentPane().add(jpButtons, java.awt.BorderLayout.CENTER);
    
  }//GEN-END:initComponents
  
  private void jchkRolloverEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkRolloverEnabledActionPerformed
    jbt.setRolloverEnabled(jchkRolloverEnabled.isSelected());
    jtb.setRolloverEnabled(jchkRolloverEnabled.isSelected());
    jchk.setRolloverEnabled(jchkRolloverEnabled.isSelected());
    jrb.setRolloverEnabled(jchkRolloverEnabled.isSelected());
  }//GEN-LAST:event_jchkRolloverEnabledActionPerformed
  
  private void jchkOpaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkOpaqueActionPerformed
    jbt.setOpaque(jchkOpaque.isSelected());
    jtb.setOpaque(jchkOpaque.isSelected());
    jchk.setOpaque(jchkOpaque.isSelected());
    jrb.setOpaque(jchkOpaque.isSelected());
  }//GEN-LAST:event_jchkOpaqueActionPerformed
  
  private void jchkFocusPaintedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFocusPaintedActionPerformed
    jbt.setFocusPainted(jchkFocusPainted.isSelected());
    jtb.setFocusPainted(jchkFocusPainted.isSelected());
    jchk.setFocusPainted(jchkFocusPainted.isSelected());
    jrb.setFocusPainted(jchkFocusPainted.isSelected());
  }//GEN-LAST:event_jchkFocusPaintedActionPerformed
  
  private void jchkEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkEnabledActionPerformed
    jbt.setEnabled(jchkEnabled.isSelected());
    jtb.setEnabled(jchkEnabled.isSelected());
    jchk.setEnabled(jchkEnabled.isSelected());
    jrb.setEnabled(jchkEnabled.isSelected());
  }//GEN-LAST:event_jchkEnabledActionPerformed
  
  private void jchkContentAreaFilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkContentAreaFilledActionPerformed
    jbt.setContentAreaFilled(jchkContentAreaFilled.isSelected());
    jtb.setContentAreaFilled(jchkContentAreaFilled.isSelected());
    jchk.setContentAreaFilled(jchkContentAreaFilled.isSelected());
    jrb.setContentAreaFilled(jchkContentAreaFilled.isSelected());
  }//GEN-LAST:event_jchkContentAreaFilledActionPerformed
  
  private void jchkBorderPaintedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBorderPaintedActionPerformed
    jbt.setBorderPainted(jchkBorderPainted.isSelected());
    jtb.setBorderPainted(jchkBorderPainted.isSelected());
    jchk.setBorderPainted(jchkBorderPainted.isSelected());
    jrb.setBorderPainted(jchkBorderPainted.isSelected());
  }//GEN-LAST:event_jchkBorderPaintedActionPerformed
  
  private void jrbBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBottomActionPerformed
    if (jrbBottom.isSelected())
      setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
  }//GEN-LAST:event_jrbBottomActionPerformed
  
  private void jrbVCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVCenterActionPerformed
    if (jrbVCenter.isSelected())
      setVerticalAlignment(javax.swing.SwingConstants.CENTER);
  }//GEN-LAST:event_jrbVCenterActionPerformed
  
  private void jrbTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTopActionPerformed
    if (jrbTop.isSelected())
      setVerticalAlignment(javax.swing.SwingConstants.TOP);
  }//GEN-LAST:event_jrbTopActionPerformed
  
  private void jrbRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRightActionPerformed
    if (jrbRight.isSelected())
      setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
  }//GEN-LAST:event_jrbRightActionPerformed
  
    private void jrbCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCenterActionPerformed
      if (jrbCenter.isSelected())
        setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }//GEN-LAST:event_jrbCenterActionPerformed
    
    private void jrbLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLeftActionPerformed
      if (jrbLeft.isSelected())
        setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    }//GEN-LAST:event_jrbLeftActionPerformed
    
    /** Set horizontal alignment */
    private void setHorizontalAlignment(int alignment) {
      jbt.setHorizontalAlignment(alignment);
      jtb.setHorizontalAlignment(alignment);
      jchk.setHorizontalAlignment(alignment);
      jrb.setHorizontalAlignment(alignment);
    }
    
    /** Set vertical alignment */
    private void setVerticalAlignment(int alignment) {
      jbt.setVerticalAlignment(alignment);
      jtb.setVerticalAlignment(alignment);
      jchk.setVerticalAlignment(alignment);
      jrb.setVerticalAlignment(alignment);
    }
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup btg1;
  private javax.swing.ButtonGroup btg2;
  private javax.swing.JPanel jpSettings;
  private javax.swing.JPanel jpAlignment;
  private javax.swing.JPanel jpHorizontalAlignment;
  private javax.swing.JRadioButton jrbLeft;
  private javax.swing.JRadioButton jrbCenter;
  private javax.swing.JRadioButton jrbRight;
  private javax.swing.JPanel jpVerticalAlignment;
  private javax.swing.JRadioButton jrbTop;
  private javax.swing.JRadioButton jrbVCenter;
  private javax.swing.JRadioButton jrbBottom;
  private javax.swing.JPanel jpMiscSettings;
  private javax.swing.JCheckBox jchkBorderPainted;
  private javax.swing.JCheckBox jchkContentAreaFilled;
  private javax.swing.JCheckBox jchkEnabled;
  private javax.swing.JCheckBox jchkFocusPainted;
  private javax.swing.JCheckBox jchkOpaque;
  private javax.swing.JCheckBox jchkRolloverEnabled;
  private javax.swing.JPanel jpButtons;
  private javax.swing.JButton jbt;
  private javax.swing.JToggleButton jtb;
  private javax.swing.JCheckBox jchk;
  private javax.swing.JRadioButton jrb;
  // End of variables declaration//GEN-END:variables
}