package exercise5_4;

public class Exercise5_4 extends javax.swing.JApplet implements Runnable {
  
  /** Creates new form Exercise5_4 */
  public Exercise5_4() {
    initComponents();
    Thread thread = new Thread(this);
    thread.start();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jProgressBar1 = new javax.swing.JProgressBar();

    getContentPane().add(jProgressBar1, java.awt.BorderLayout.NORTH);

  }//GEN-END:initComponents

  public void run() {
    while (true) {
      try {
        Thread.sleep(500);
      }
      catch (InterruptedException ex) { }

      jProgressBar1.setValue((int)(jProgressBar1.getMaximum()*
        Math.random()));
    }
  }  
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JProgressBar jProgressBar1;
  // End of variables declaration//GEN-END:variables
  
}
