package clockdemo;

public class SixClocks extends javax.swing.JApplet {
  
  /** Creates new form SixClocks */
  public SixClocks() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    private void initComponents() {//GEN-BEGIN:initComponents
        clock1 = new clockdemo.Clock();
        clock2 = new clockdemo.Clock();
        clock3 = new clockdemo.Clock();
        clock4 = new clockdemo.Clock();
        clock5 = new clockdemo.Clock();
        clock6 = new clockdemo.Clock();

        getContentPane().setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        clock1.setDateStyle(2);
        clock1.setHeader("London");
        clock1.setTimeZoneID("GMT");
        getContentPane().add(clock1);

        clock2.setHeader("Paris");
        clock2.setTimeZoneID("Europe/Paris");
        getContentPane().add(clock2);

        getContentPane().add(clock3);

        clock4.setHeader("Chicago");
        clock4.setTimeZoneID("CST");
        getContentPane().add(clock4);

        clock5.setHeader("Denver");
        clock5.setTimeZoneID("MST");
        getContentPane().add(clock5);

        clock6.setHeader("San Francisco");
        clock6.setTimeZoneID("PST");
        getContentPane().add(clock6);

    }//GEN-END:initComponents
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private clockdemo.Clock clock6;
    private clockdemo.Clock clock5;
    private clockdemo.Clock clock4;
    private clockdemo.Clock clock3;
    private clockdemo.Clock clock2;
    private clockdemo.Clock clock1;
    // End of variables declaration//GEN-END:variables
}