package exercise6_6;

import javax.swing.*;

public class Exercise6_6 extends javax.swing.JApplet {
  
  /** Creates new form Exercise6_6 */
  public Exercise6_6() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jrbTop = new javax.swing.JRadioButton();
    jrbLeft = new javax.swing.JRadioButton();
    jrbRight = new javax.swing.JRadioButton();
    jrbBottom = new javax.swing.JRadioButton();
    jtpFigures = new javax.swing.JTabbedPane();
    figurePanel1 = new exercise6_5.FigurePanel();
    figurePanel2 = new exercise6_5.FigurePanel();
    figurePanel3 = new exercise6_5.FigurePanel();
    figurePanel4 = new exercise6_5.FigurePanel();

    jPanel1.setBorder(new javax.swing.border.TitledBorder("Specify Tab Location"));
    jrbTop.setText("Top");
    buttonGroup1.add(jrbTop);
    jrbTop.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jrbTopActionPerformed(evt);
      }
    });

    jPanel1.add(jrbTop);

    jrbLeft.setText("Left");
    buttonGroup1.add(jrbLeft);
    jrbLeft.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jrbLeftActionPerformed(evt);
      }
    });

    jPanel1.add(jrbLeft);

    jrbRight.setText("Right");
    buttonGroup1.add(jrbRight);
    jrbRight.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jrbRightActionPerformed(evt);
      }
    });

    jPanel1.add(jrbRight);

    jrbBottom.setText("Bottom");
    buttonGroup1.add(jrbBottom);
    jrbBottom.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jrbBottomActionPerformed(evt);
      }
    });

    jPanel1.add(jrbBottom);

    getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

    jtpFigures.addTab("Square", figurePanel1);

    figurePanel2.setFigureType(2);
    jtpFigures.addTab("Rectangle", figurePanel2);

    figurePanel3.setFigureType(3);
    jtpFigures.addTab("Circle", figurePanel3);

    figurePanel4.setFigureType(4);
    jtpFigures.addTab("Oval", figurePanel4);

    getContentPane().add(jtpFigures, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents

  private void jrbBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBottomActionPerformed
    jtpFigures.setTabPlacement(JTabbedPane.BOTTOM);
  }//GEN-LAST:event_jrbBottomActionPerformed

  private void jrbRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRightActionPerformed
    jtpFigures.setTabPlacement(JTabbedPane.RIGHT);
  }//GEN-LAST:event_jrbRightActionPerformed

  private void jrbLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLeftActionPerformed
    jtpFigures.setTabPlacement(JTabbedPane.LEFT);
  }//GEN-LAST:event_jrbLeftActionPerformed

  private void jrbTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTopActionPerformed
    jtpFigures.setTabPlacement(JTabbedPane.TOP);
  }//GEN-LAST:event_jrbTopActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private exercise6_5.FigurePanel figurePanel4;
  private exercise6_5.FigurePanel figurePanel3;
  private exercise6_5.FigurePanel figurePanel2;
  private exercise6_5.FigurePanel figurePanel1;
  private javax.swing.JRadioButton jrbBottom;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JRadioButton jrbRight;
  private javax.swing.JRadioButton jrbTop;
  private javax.swing.JTabbedPane jtpFigures;
  private javax.swing.JRadioButton jrbLeft;
  // End of variables declaration//GEN-END:variables
  
}
